### PR TITLE
Overwrite the command/function in the vim plugin

### PR DESCRIPTION
**Pull request by RobertAudi**
If the vim plugin is sourced twice, this error will be thrown:

~~~
E174: Command already exists: add ! to replace it
line   16:
E122: Function <SNR>84_YcmGenerateConfig already exists, add ! to replace it
~~~

### CODE REVIEW

**Comment by rdnetto** [comment]
Under what circumstances would the plugin be sourced twice?

**Comment by RobertAudi** [comment]
I am using [vim-plug](https://github.com/junegunn/vim-plug) for managing plugins. Whenever I run the install command, vim-plug sources the runtime path so that the user doesn't have to restart vim to see the changes. That's when the error occurs. I wouldn't be surprised if other plugin managers do the same thing.

**Comment by rdnetto** [comment]
Ok, lgtm.

For future reference though, please submit PRs against the ```develop``` branch.

**Comment by RobertAudi** [comment]
Ah sorry about the branch mismatch. I made the whole thing from github (I even made a Pull Request to my own fork by mistake ...)

Anyway, thanks for the merge :+1:

**Pull request closed without merging**
