### PR TITLE
allow for passing through environment variables to fakebuild process

### PR DESCRIPTION
**Pull request by aumuell**
The build process for a project I am working on requires that some environment variables be set.
I added the options -e/--environment for adding a comma separated list of environment variables to pass to the build command.

### CODE REVIEW

**Comment by rdnetto** [comment]
Is there a reason to restrict it to only passing those variables through? Simply passing them all through reduces the flag to a boolean, and simplifies the code. (You could initialize env to the current variables, and convert the initializer to a series of assignments.)

**Comment by aumuell** [comment]
Not for me. As you did not do it in the first place, I assumed that you might want have more control over it. I will try to update this pull request accordingly.

**Comment by rdnetto** [comment]
I was just being concise/minimal. More control = more annoying UI code, so I prefer to avoid it unless it's necessary. :P

On second thoughts, a better option might be to define a -D flag similar to cmake which accepted key-value pairs. e.g. `-D name=value -D foo=bar`

BTW, you may want to rebase your branch, as I rebased develop recently.

**Comment by aumuell** [comment]
A solution along the lines of `-D name=value -D foo=bar` would be overkill for me: I would have to write `-D ENVVAR1=${ENVVAR1} -D ENVVAR2=${ENVVAR2} -D ENVVAR3=${ENVVAR3}`. That's quite cumbersome.

I think such an option is perhaps a useful supplement to passing on the complete environment, but not an alternative.

**Comment by rdnetto** [comment]
You make a valid point. I was approaching it from the perspective that you wouldn't need to define them in the environment if using `-D`, but I suppose you probably already have them defined for the purpose of actually building it. (And you can always define them when running YCM-Gen anyway through the normal shell mechanism.)

Let's go with the `-e` approach.

**Comment by rdnetto** [comment]
Merged b19a78b21 (with some minor fixups)

**Pull request closed without merging**
