### PR TITLE
Stdout parsing as an option

### PR DESCRIPTION
**Pull request by TotalKrill**
Added stdout parsing as an option, what it does is that it currently parses the output of the "make" command and then tries to parse the flags from there. The added option -B can serve to only use the lines from stdout that starts with a defined string. 

This is very useful for embedded programs, where clang can't handle the compilation. I am using this succesfully on a ChibiOs project. Instead of going through all the defines and such, this was a lot easier. 

Without the -s flag, the program is executing the same as before

### CODE REVIEW

**Comment by rdnetto** [comment]
> This is very useful for embedded programs, where clang can't handle the compilation. I am using this succesfully on a ChibiOs project. Instead of going through all the defines and such, this was a lot easier.

If clang can't compile the project, how exactly does this work with YCM?

(Note to self: re-raised from #75).

**Comment by TotalKrill** [comment]
Well, YCM just needs the flags for compilation and finding the correct source files. Therefore it doesnt really matter how it is compiled in this case, arm-none-eabi-gcc is just gcc for the arm world. The parsing check from clang still works since the language is still C, just that the compiler is different.

**Comment by TotalKrill** [comment]
If you want to test against something, you can test against 
[Chibios](https://github.com/ChibiOS/ChibiOS)

You need the arm-none-eabi-gcc compiler, and then you should be able to test on any of the 
examples under `testhal/`
ie `testhal/STM32F37x/ADC/`

By invoking the following command:
`./config_gen.py  -s -B arm-none-eabi-gcc -x c .`

**Comment by TotalKrill** [comment]
hmm, I just realised that clang can compile the program( apart for some special flags for this compiler, but that is just to force with the -i flag) , its just that since it isnt using the CC environment variable (due to being a special version of gcc) it isnt trying to compile it with clang, but rather uses a compiler defined in the Makefile. 

Maybe there is a better way to do it, but using the CC env variables isnt an option in this case, and since the program needs this specific C compiler, I cant think of any. There is a few of the embedded programs that actually defines the compiler this way(chibios, contiki etc), and using the stdout from the makefile will work on most of them. 

So i still consider this a viable option, although you will have to manually specify the language when calling the script.

**Comment by rdnetto** [comment]
> hmm, I just realised that clang can compile the program( apart for some special flags for this compiler, but that is just to force with the -i flag) , its just that since it isnt using the CC environment variable (due to being a special version of gcc) it isnt trying to compile it with clang, but rather uses a compiler defined in the Makefile.

I took a look at [one](https://github.com/ChibiOS/ChibiOS/blob/master/testhal/AVR/I2C/Makefile), and the Makefile doesn't hardcode the path of the compiler, just its filename. That means there's a much simpler solution available: create symlinks in `fake-toolchain/Unix/` from `avr-gcc`, etc. to `cc`, and from `avr-g++` to `cxx` (if applicable). Then you should be able to invoke YCM-Gen normally. I just tried it out and it looks like it works perfectly.

**Comment by TotalKrill** [comment]
Yes, this is indeed a much better solution. Will you add these to the stable branch? 

arm-none-eabi-gcc -> cc
arm-none-eabi-g++ -> cxx
avr-gcc -> cc
avr-g++ -> cxx

**Comment by rdnetto** [comment]
Sorry, but I'd prefer not to. There is a practically unlimited no. of possible compiler names, and I'd rather not try and keep a list of all of them in the repo.

I don't see this being a particularly large issue in practice, as git will simply ignore the extra files when pulling updates, and each user who actually needs this functionality will likely need a different compiler name anyway.

**Comment by TotalKrill** [comment]
Well, id like to argue against that, because well the variations of gcc like:

avr-gcc, arm-none-eabi-gcc, mips-linux-gnu-gcc and sdcc ( the gcc for pic as i understand it) 

are the ones mostly used by programmers that run vim. The other compilers are often tied to different IDEs, or a bit special to install anyway. 

So maybe not supporting all compilers, but at least the derivatives of gcc. It isnt that much extra then. Me and my collegues would most certainly enjoy it :)

**Comment by korken89** [comment]
+1 from another embedded developer here. This would be awesome and make it much more useful directly.
The 4 compilers listed by @TotalKrill are the main used, with this it would reach 95% of the audience.

**Comment by rdnetto** [comment]
In a change of heart,  I've merged #80, which should address this. If anyone needs another commonly used arch, please feel free to open a PR for it.

**Comment by Osteri** [comment]
@rdnetto Have you forgot adding this feature to the master branch? It would be cool to have by default.

**Comment by rdnetto** [comment]
There is no master branch. :)

The change is in `dev`, but I haven't merged it into `stable` in a while. I really should, but I want to setup some proper CI to detect Python 2/3 compatibility issues before doing so since I'm certain there are some subtle bugs waiting in there.

**Pull request closed without merging**
