### PR TITLE
Added meson + ninja support

### LINKED ISSUE #51: support for meson build system
I'm trying out [meson](https://github.com/mesonbuild/meson) for a few pet projects and I was hoping if YCM-Generator could support it. It generates a `compile_command.json`, just like CMake does, of such format - 

```
[
  {
    "directory": "/home/agauniyal/projects/rang/build",
    "command": "ccache c++  '-pipe' '-Wall' '-Winvalid-pch' '-Wnon-virtual-dtor' '-std=c++11' '-g' '-Itest/RCBTest@exe' '-I../test' '-Itest' '-Iinclude' '-I../include' '-MMD' '-MQ' 'test/RCBTest@exe/RCBTest.cpp.o' '-MF' 'test/RCBTest@exe/RCBTest.cpp.o.d' -o 'test/RCBTest@exe/RCBTest.cpp.o' -c ../test/RCBTest.cpp",
    "file": "../test/RCBTest.cpp"
  },
  {
    "directory": "/home/agauniyal/projects/rang/build",
    "command": "ccache c++  '-pipe' '-Wall' '-Winvalid-pch' '-Wnon-virtual-dtor' '-std=c++11' '-g' '-Itest/VTest@exe' '-I../test' '-Itest' '-Iinclude' '-I../include' '-MMD' '-MQ' 'test/VTest@exe/visualTest.cpp.o' '-MF' 'test/VTest@exe/visualTest.cpp.o.d' -o 'test/VTest@exe/visualTest.cpp.o' -c ../test/visualTest.cpp",
    "file": "../test/visualTest.cpp"
  }
]
```

### PR DESCRIPTION
**Pull request by vyasgiridhar**
This Adds Meson + Ninja support.

Other backends like Cmake + Ninja can be added later.

this fixes #51

### CODE REVIEW

**Comment by rdnetto** [comment]
Look good. Can you update the README to mention meson support, and to also list an example project using meson that we can use for testing?

**Comment by rdnetto** [comment]
One last thing: can you merge `develop` back into your branch? I just configured CI for this repo and would like to make sure the builds are green before merging it in.

**Comment by vyasgiridhar** [comment]
Done

**Comment by rdnetto** [comment]
Merged, thanks for the PR. :)

**Pull request merged**
